import os
from datetime import datetime
from fpdf import FPDF, XPos, YPos
# PDF REPORT CLASS
class MedicalReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(26, 26, 46)
        self.set_text_color(255, 255, 255)
        self.rect(0, 0, 210, 25, "F")
        self.cell(
            0, 15,
            "NEURODETECT - AI BRAIN TUMOR REPORT",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C"
        )
        self.set_text_color(0, 0, 0)
        self.ln(5)
    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(
            0, 5,
            "DISCLAIMER: This report is AI generated "
            "and does not replace professional medical "
            "diagnosis. Consult a qualified physician.",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C"
        )
        self.cell(
            0, 5,
            f"Page {self.page_no()} | "
            f"Generated by NeuroDetect AI | "
            f"Confidential Medical Document",
            align="C"
        )
    def section_title(self, title):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(0, 210, 255)
        self.set_text_color(0, 0, 0)
        self.cell(
            0, 8, f"  {title}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            fill=True
        )
        self.ln(2)

    def info_row(self, label, value, bold=False):
        self.set_font("Helvetica", "B", 10)
        self.cell(60, 7, f"{label}:", border=0)
        if bold:
            self.set_font("Helvetica", "B", 10)
        else:
            self.set_font("Helvetica", "", 10)
        self.cell(
            0, 7, str(value),
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )

# ─────────────────────────────────────────
# GENERATE REPORT
# ─────────────────────────────────────────
def generate_pdf_report(
    patient_name,
    patient_age,
    patient_gender,
    doctor_name,
    prediction,
    confidence,
    risk_level,
    tumor_size,
    stage,
    icd10_code,
    treatment_info,
    gradcam_path = None,
    save_path    = None
):
    os.makedirs("reports", exist_ok=True)

    if save_path is None:
        timestamp = datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )
        save_path = (
            f"reports/medical_report_"
            f"{patient_name.replace(' ', '_')}_"
            f"{timestamp}.pdf"
        )

    pdf = MedicalReport()
    pdf.add_page()

    # Report Info
    pdf.section_title("REPORT INFORMATION")
    pdf.info_row(
        "Report Date",
        datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    pdf.info_row(
        "Report ID",
        f"NDR-{datetime.now().strftime('%Y%m%d%H%M%S')}"
    )
    pdf.info_row("Generated By", "NeuroDetect AI v1.0")
    pdf.info_row("Reviewing Doctor", doctor_name)
    pdf.ln(3)

    # Patient Info
    pdf.section_title("PATIENT INFORMATION")
    pdf.info_row("Patient Name",   patient_name)
    pdf.info_row("Age",            patient_age)
    pdf.info_row("Gender",         patient_gender)
    pdf.info_row("Scan Type",      "Brain MRI")
    pdf.info_row(
        "Scan Date",
        datetime.now().strftime("%Y-%m-%d")
    )
    pdf.ln(3)

    # AI Diagnosis
    pdf.section_title("AI DIAGNOSIS RESULTS")
    pdf.info_row(
        "Diagnosis",
        prediction.upper(),
        bold=True
    )
    pdf.info_row("ICD-10 Code",   icd10_code)
    pdf.info_row(
        "AI Confidence", f"{confidence:.1f}%"
    )
    pdf.info_row("Risk Level",    risk_level)
    pdf.info_row("Tumor Size",    tumor_size)
    pdf.info_row("WHO Stage",     stage)
    pdf.info_row(
        "Clinical Urgency",
        treatment_info.get(
            "urgency", "N/A"
        ).replace("\u2014", "-")
    )
    pdf.ln(3)

    # Treatment
    pdf.section_title("TREATMENT ADVISORY (NCCN)")
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(
        0, 7, "First Line Treatment:",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )
    pdf.set_font("Helvetica", "", 10)
    for t in treatment_info.get("first_line", []):
        pdf.cell(
            0, 6, f"    -> {t}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )
    pdf.ln(2)

    if treatment_info.get("second_line"):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(
            0, 7, "Second Line Treatment:",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )
        pdf.set_font("Helvetica", "", 10)
        for t in treatment_info["second_line"]:
            pdf.cell(
                0, 6, f"    -> {t}",
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT
            )
        pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(
        0, 7, "Key Medications:",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )
    pdf.set_font("Helvetica", "", 10)
    for d in treatment_info.get("drugs", []):
        pdf.cell(
            0, 6, f"    -> {d}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(
        0, 7, "Recommended Specialists:",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )
    pdf.set_font("Helvetica", "", 10)
    for s in treatment_info.get("specialists", []):
        pdf.cell(
            0, 6, f"    -> {s}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(
        0, 7, "Follow Up Schedule:",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )
    pdf.set_font("Helvetica", "", 10)
    for f in treatment_info.get("follow_up", []):
        pdf.cell(
            0, 6, f"    -> {f}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )
    pdf.ln(3)

    # Survival Stats
    pdf.section_title("SURVIVAL STATISTICS")
    pdf.set_font("Helvetica", "", 10)
    for k, v in treatment_info.get(
        "survival", {}
    ).items():
        pdf.cell(
            0, 6, f"    -> {k}: {v}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )
    pdf.ln(3)

    # Grad-CAM
    if gradcam_path and os.path.exists(gradcam_path):
        pdf.section_title("GRAD-CAM VISUALIZATION")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(
            0, 6,
            "Red regions indicate AI attention "
            "areas (likely tumor location)",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )
        pdf.ln(2)
        try:
            pdf.image(gradcam_path, x=15, w=180)
        except:
            pdf.cell(
                0, 6,
                "Grad-CAM image unavailable",
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT
            )
        pdf.ln(3)

    # Clinical Trials
    pdf.section_title("CLINICAL TRIALS")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(
        0, 6,
        treatment_info.get(
            "clinical_trials",
            "Not applicable"
        )
    )
    pdf.ln(3)

    # Disclaimer
    pdf.section_title("MEDICAL DISCLAIMER")
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(128, 0, 0)
    pdf.multi_cell(
        0, 6,
        "This report has been generated by "
        "NeuroDetect AI system for preliminary "
        "screening purposes only. It is not a "
        "definitive medical diagnosis. All findings "
        "must be reviewed and confirmed by a "
        "qualified neurologist or radiologist. "
        "Treatment decisions must be made by "
        "licensed medical professionals based on "
        "complete clinical evaluation."
    )

    pdf.output(save_path)
    print(f"✅ PDF Report saved: {save_path}")
    return save_path

if __name__ == "__main__":
    from treatment_advisor import get_treatment_info

    treatment = get_treatment_info("glioma")

    path = generate_pdf_report(
        patient_name   = "John Doe",
        patient_age    = "45",
        patient_gender = "Male",
        doctor_name    = "Dr. Smith",
        prediction     = "glioma",
        confidence     = 95.0,
        risk_level     = "CRITICAL",
        tumor_size     = "Large >4cm",
        stage          = "Grade IV Malignant",
        icd10_code     = "C71.9",
        treatment_info = treatment,
        gradcam_path   = "reports/gradcam_glioma.png"
    )
    print(f"✅ Report generated: {path}")
